# Generated by Django 2.2.27 on 2023-06-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.IntegerField(null=True, verbose_name='创建人')),
                ('modify_by', models.IntegerField(null=True, verbose_name='修改人')),
                ('state', models.IntegerField(default=0, verbose_name='禁用状态')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='客户名称')),
                ('telephone1', models.CharField(default=None, max_length=11, verbose_name='手机号码1')),
                ('telephone2', models.CharField(default=None, max_length=11, verbose_name='手机号码2')),
                ('email', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='邮箱')),
                ('address', models.CharField(default=None, max_length=200, verbose_name='地址')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
                'db_table': 'pnw_accounts',
                'ordering': ['-id'],
            },
        ),
    ]
