# Generated by Django 2.2.27 on 2023-06-02 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.IntegerField(null=True, verbose_name='创建人')),
                ('modify_by', models.IntegerField(null=True, verbose_name='修改人')),
                ('state', models.IntegerField(default=0, verbose_name='禁用状态')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='原材料名称')),
                ('code', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='编码')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='单价')),
                ('vendor', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='厂商')),
            ],
            options={
                'verbose_name': '原材料信息',
                'verbose_name_plural': '原材料信息',
                'db_table': 'pnw_material',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.IntegerField(null=True, verbose_name='创建人')),
                ('modify_by', models.IntegerField(null=True, verbose_name='修改人')),
                ('state', models.IntegerField(default=0, verbose_name='禁用状态')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='仓库名称')),
                ('category', models.SmallIntegerField(choices=[(0, '成品仓'), (1, '原材料仓')], default=0, verbose_name='仓库类型')),
                ('telephone1', models.CharField(default=None, max_length=11, verbose_name='联系方式1')),
                ('telephone2', models.CharField(default=None, max_length=11, verbose_name='联系方式2')),
            ],
            options={
                'verbose_name': '仓库信息',
                'verbose_name_plural': '仓库信息',
                'db_table': 'pnw_warehouses',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='accounts',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='客户名称'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.IntegerField(null=True, verbose_name='创建人')),
                ('modify_by', models.IntegerField(null=True, verbose_name='修改人')),
                ('state', models.IntegerField(default=0, verbose_name='禁用状态')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='成品名称')),
                ('code', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='编码')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='产品价格')),
                ('sellprice', models.FloatField(blank=True, null=True, verbose_name='产品售价')),
                ('materials', models.ManyToManyField(blank=True, db_table='pnw_product_to_material', to='pnwdb.Materials', verbose_name='产品原材料关系表')),
            ],
            options={
                'verbose_name': '成品信息',
                'verbose_name_plural': '成品信息',
                'db_table': 'pnw_product',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Inventory_prdt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.IntegerField(null=True, verbose_name='创建人')),
                ('modify_by', models.IntegerField(null=True, verbose_name='修改人')),
                ('state', models.IntegerField(default=0, verbose_name='禁用状态')),
                ('count', models.IntegerField(verbose_name='剩余数量')),
                ('inbound', models.IntegerField(verbose_name='待入库数量')),
                ('outbound', models.IntegerField(verbose_name='待出库数量')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pnwdb.Products', verbose_name='成品')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pnwdb.Warehouses', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '成品库存信息',
                'verbose_name_plural': '成品库存信息',
                'db_table': 'pnw_inventory_prdt',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Inventory_mtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.IntegerField(null=True, verbose_name='创建人')),
                ('modify_by', models.IntegerField(null=True, verbose_name='修改人')),
                ('state', models.IntegerField(default=0, verbose_name='禁用状态')),
                ('count', models.IntegerField(verbose_name='剩余数量')),
                ('inbound', models.IntegerField(verbose_name='待入库数量')),
                ('outbound', models.IntegerField(verbose_name='待出库数量')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pnwdb.Materials', verbose_name='原材料')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pnwdb.Warehouses', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '原材料库存信息',
                'verbose_name_plural': '原材料库存信息',
                'db_table': 'pnw_inventory_mtrl',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='accounts',
            name='opportunitys',
            field=models.ManyToManyField(blank=True, db_table='pnw_opportunity', to='pnwdb.Products', verbose_name='客户意向表'),
        ),
    ]
