# Generated by Django 2.2.27 on 2023-06-02 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pnwdb', '0002_auto_20230602_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.IntegerField(null=True, verbose_name='创建人')),
                ('modify_by', models.IntegerField(null=True, verbose_name='修改人')),
                ('state', models.IntegerField(default=0, verbose_name='禁用状态')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='订单总价')),
                ('address', models.CharField(default=None, max_length=200, verbose_name='收货地址')),
                ('status', models.SmallIntegerField(choices=[(0, '待发货'), (1, '已发货'), (2, '中止'), (3, '超时'), (4, '其他')], default=0, verbose_name='发货状态')),
                ('innerstatus', models.SmallIntegerField(choices=[(0, '装配中'), (1, '采购中'), (2, '其他')], default=0, verbose_name='内部状态')),
                ('deliverlevel', models.SmallIntegerField(choices=[(0, '重要'), (1, '一般'), (2, '紧急')], default=0, verbose_name='发货优先级')),
                ('logistics', models.CharField(max_length=50, verbose_name='物流单号')),
                ('deliverdate', models.DateField(blank=True, null=True, verbose_name='预估交付日期')),
                ('isgather', models.BooleanField(verbose_name='是否已全部回款')),
                ('receivedmoney', models.FloatField(blank=True, null=True, verbose_name='已收金额')),
                ('payway', models.SmallIntegerField(choices=[(0, '现金'), (1, '微信'), (2, '支付宝'), (3, '信用卡'), (4, '其他')], default=0, verbose_name='支付方式')),
                ('ticketnumber', models.CharField(max_length=50, unique=True, verbose_name='发票号')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pnwdb.Accounts', verbose_name='下单客户')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processor', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('responsibleuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsibleuser', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'pnw_order',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Inventoryrecord_prdt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.IntegerField(null=True, verbose_name='创建人')),
                ('modify_by', models.IntegerField(null=True, verbose_name='修改人')),
                ('state', models.IntegerField(default=0, verbose_name='禁用状态')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='出入库编号')),
                ('ordername', models.CharField(blank=True, max_length=50, null=True, verbose_name='订单号')),
                ('assemblyname', models.CharField(blank=True, max_length=50, null=True, verbose_name='装配单号')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('direction', models.SmallIntegerField(choices=[(0, '入库'), (1, '出库')], default=0, verbose_name='出入库')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pnwdb.Products', verbose_name='成品')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pnwdb.Warehouses', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '成品出入库记录',
                'verbose_name_plural': '成品出入库记录',
                'db_table': 'pnw_inventoryrecord_prdt',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Inventoryrecord_mtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.IntegerField(null=True, verbose_name='创建人')),
                ('modify_by', models.IntegerField(null=True, verbose_name='修改人')),
                ('state', models.IntegerField(default=0, verbose_name='禁用状态')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='出入库编号')),
                ('purchasername', models.CharField(blank=True, max_length=50, null=True, verbose_name='采购单号')),
                ('assemblyname', models.CharField(blank=True, max_length=50, null=True, verbose_name='装配单号')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('direction', models.SmallIntegerField(choices=[(0, '入库'), (1, '出库')], default=0, verbose_name='出入库')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pnwdb.Materials', verbose_name='原材料')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pnwdb.Warehouses', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '原材料出入库记录',
                'verbose_name_plural': '原材料出入库记录',
                'db_table': 'pnw_inventoryrecord_mtrl',
                'ordering': ['-id'],
            },
        ),
    ]
