# Generated by Django 2.2.27 on 2023-06-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdb', '0003_inventoryrecord_mtrl_inventoryrecord_prdt_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ticketnumber',
            field=models.CharField(max_length=50, verbose_name='发票号'),
        ),
    ]
