# Generated by Django 2.2.27 on 2023-06-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdb', '0005_assemblyorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyorder',
            name='assemblyproduct',
            field=models.ManyToManyField(blank=True, db_table='pnw_assembly_product', to='pnwdb.Products', verbose_name='装配产品关系表'),
        ),
    ]
