# Generated by Django 2.2.27 on 2023-06-02 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdb', '0007_purchaseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblyorder',
            name='assemblyproduct',
        ),
        migrations.CreateModel(
            name='assemblyproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.IntegerField(null=True, verbose_name='创建人')),
                ('modify_by', models.IntegerField(null=True, verbose_name='修改人')),
                ('state', models.IntegerField(default=0, verbose_name='禁用状态')),
                ('count', models.IntegerField(verbose_name='产品装配数量')),
                ('assemblyorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnwdb.AssemblyOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnwdb.Products')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
