# Generated by Django 2.2.27 on 2023-06-02 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdb', '0009_auto_20230602_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyproduct',
            name='assemblyorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnwdb.AssemblyOrder'),
        ),
        migrations.AlterField(
            model_name='purchasematerial',
            name='purchaseorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnwdb.PurchaseOrder'),
        ),
        migrations.AlterModelTable(
            name='assemblyproduct',
            table='pnw_assembly_to_product',
        ),
        migrations.AlterModelTable(
            name='purchasematerial',
            table='pnw_purchase_to_material',
        ),
    ]
