# Generated by Django 2.2.27 on 2023-06-06 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnwdb', '0014_auto_20230605_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='assemblyorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='assemblyorder',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='inventory_mtrl',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventory_mtrl',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='inventory_prdt',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventory_prdt',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='inventoryrecord_mtrl',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventoryrecord_mtrl',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='inventoryrecord_prdt',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventoryrecord_prdt',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='warehouses',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='warehouses',
            name='modify_by',
        ),
        migrations.AlterField(
            model_name='assemblyproduct',
            name='assemblyorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnwdb.AssemblyOrder'),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_created_by', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='products',
            name='modify_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_modify_by', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='purchasematerial',
            name='purchaseorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnwdb.PurchaseOrder'),
        ),
    ]
