# Generated by Django 2.2.27 on 2023-06-01 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0003_remove_roles_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='created_by1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='部门'),
        ),
    ]
