# Generated by Django 2.2.27 on 2023-06-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_departments_created_by1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='created_by1',
        ),
    ]
