# Generated by Django 2.2.27 on 2023-06-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20230601_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='created_by',
            field=models.IntegerField(null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='departments',
            name='modify_by',
            field=models.IntegerField(null=True, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='permissions',
            name='created_by',
            field=models.IntegerField(null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='permissions',
            name='modify_by',
            field=models.IntegerField(null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='created_by',
            field=models.IntegerField(null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='modify_by',
            field=models.IntegerField(null=True, verbose_name='修改人'),
        ),
    ]
