# Generated by Django 2.2.27 on 2023-06-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20230601_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='state',
            field=models.IntegerField(default=0, verbose_name='禁用状态'),
        ),
        migrations.AddField(
            model_name='permissions',
            name='state',
            field=models.IntegerField(default=0, verbose_name='禁用状态'),
        ),
        migrations.AddField(
            model_name='roles',
            name='state',
            field=models.IntegerField(default=0, verbose_name='禁用状态'),
        ),
    ]
