# Generated by Django 2.2.27 on 2023-06-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20230602_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='created_by',
            field=models.IntegerField(default=0, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='created_by',
            field=models.IntegerField(default=0, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='created_by',
            field=models.IntegerField(default=0, null=True, verbose_name='创建人'),
        ),
    ]
