# Generated by Django 2.2.27 on 2023-06-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_auto_20230605_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='modify_by',
        ),
    ]
