# Generated by Django 2.2.27 on 2023-06-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20210306_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='created_by',
            field=models.IntegerField(null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='assets',
            name='modify_by',
            field=models.IntegerField(null=True, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='cabinets',
            name='created_by',
            field=models.IntegerField(null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='cabinets',
            name='modify_by',
            field=models.IntegerField(null=True, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='idc',
            name='created_by',
            field=models.IntegerField(null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='idc',
            name='modify_by',
            field=models.IntegerField(null=True, verbose_name='修改人'),
        ),
    ]
