# Generated by Django 2.2.27 on 2023-06-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20230605_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='cabinets',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cabinets',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='modify_by',
        ),
    ]
