# Generated by Django 2.2.27 on 2023-06-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_onlineusers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlogs',
            name='created_by',
            field=models.IntegerField(null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='errorlogs',
            name='modify_by',
            field=models.IntegerField(null=True, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='ipblacklist',
            name='created_by',
            field=models.IntegerField(null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='ipblacklist',
            name='modify_by',
            field=models.IntegerField(null=True, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='onlineusers',
            name='created_by',
            field=models.IntegerField(null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='onlineusers',
            name='modify_by',
            field=models.IntegerField(null=True, verbose_name='修改人'),
        ),
    ]
