# Generated by Django 2.2.27 on 2023-06-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20230605_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlogs',
            name='modify_by',
            field=models.IntegerField(default=0, null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='ipblacklist',
            name='modify_by',
            field=models.IntegerField(default=0, null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='onlineusers',
            name='modify_by',
            field=models.IntegerField(default=0, null=True, verbose_name='修改人'),
        ),
    ]
