# Generated by Django 2.2.27 on 2023-06-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20230605_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlogs',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='errorlogs',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='ipblacklist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ipblacklist',
            name='modify_by',
        ),
        migrations.RemoveField(
            model_name='onlineusers',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='onlineusers',
            name='modify_by',
        ),
    ]
